# Generated by Django 5.1.3 on 2024-12-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.departmentmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='divison',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.divisionmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.institutionmodel'),
        ),
    ]
